name: cider_off
description: "CiderOff - Делаем Сидр."
publish_to: 'none'
version: 1.0.3+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# База данных и состояние
  provider: ^6.1.2
  path_provider: ^2.1.2

  # Генерация PDF и печать этикеток
  pdf: ^3.10.8
  printing: ^5.13.0

  # Напоминания и календарь
  device_calendar: ^4.3.2
 # Пуш уведомления 
  flutter_local_notifications: ^17.2.3
  # flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  flutter_timezone: ^2.0.0
  # Импорт/Экспорт, работы с файлами
  share_plus: ^10.0.0
  file_picker: ^8.1.4
  uuid: ^4.3.3
  intl: ^0.20.3
  
  # Построение наглядных графиков
  fl_chart: ^0.68.0
  
  # ... остальные зависимости ...
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqlite3: ^2.4.0
  path: ^1.9.0

  webdav_client: ^1.1.2  # Клиент для работы по протоколу WebDAV

  google_sign_in: ^6.2.1
  googleapis: ^13.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.1
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Ассеты для дефолтных рецептов и макетов
  assets:
    - assets/default_recipes/
    - assets/default_templates/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  # Для Android 8.0+ (adaptive icons) можно задать фон:
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/images/icon_foreground.png    
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 256 #