# Объединенные параметры JVM без дублирования
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED

# Флаги AndroidX
android.useAndroidX=true

# Настройки сборки Kotlin
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process

# Экранированный путь к JDK/JBR Android Studio
org.gradle.java.home=D\:/Program Files/Android/Android Studio/jbr

# Флаги мигратора Flutter
android.builtInKotlin=true
android.newDsl=false